routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\CustoController;
use App\Http\Controllers\SalarioController;
use App\Http\Controllers\PlanosController;
use App\Http\Controllers\ServicoAgenciadoController;
use App\Http\Controllers\BaseCustoController;
use App\Http\Controllers\CadastroDiversosFinancController;
use App\Http\Controllers\ContaController;
use App\Http\Controllers\CentroCustoController;
use App\Http\Controllers\CategoriaLancController;
use App\Http\Controllers\SubCategoriaLancController;
use App\Http\Controllers\LancamentoController;
use App\Http\Controllers\ReceitasController;
use App\Http\Controllers\DespesasController;
use App\Http\Controllers\FornecedoresController;
use App\Http\Controllers\PropostasController;
use App\Http\Controllers\LeadsController;
use App\Http\Controllers\GestaoAnuncioController;
use App\Http\Controllers\LinhaEditorialController;
use App\Http\Controllers\ProspeccaoController;
use App\Http\Controllers\ConversaController;
use App\Http\Controllers\ConsultoriaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ContratoController;
use App\Http\Controllers\ApresentacaoController;
use App\Http\Controllers\ContaBancariaController;
use App\Http\Controllers\PlataformaController;
use App\Http\Controllers\PlataformaItensController;
use App\Http\Controllers\GoogleAdsController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\PlanoGestaoController;
use App\Http\Livewire\Leads;



Auth::routes();
Route::get('/', [HomeController::class, 'index'])->name('home');



Route::group(['prefix' => 'pdf'], function () {
    Route::get('resumo/{id}', [PdfController::class, 'resumo'])->name('pdf.resumo');
    Route::get('recibo/{id}', [PdfController::class, 'recibo'])->name('pdf.recibo');
});



Route::group(['prefix' => 'gestao-financeira'], function () {
    Route::resource('custos', CustoController::class);
    Route::resource('custos-salarios', SalarioController::class);
    Route::resource('planos', PlanosController::class);
    Route::resource('servicos-agenciado', ServicoAgenciadoController::class);
    Route::resource('base-custos', BaseCustoController::class);
    Route::get('cadastros-diversos', [CadastroDiversosFinancController::class, 'index'])->name('cadastros.diversos');
    Route::resource('plano-contas', ContaController::class);
    Route::resource('centro-custos', CentroCustoController::class);
    Route::resource('categorias', CategoriaLancController::class);
    Route::resource('subcategorias', SubCategoriaLancController::class);
    Route::resource('lancamentos', LancamentoController::class);

    Route::resource('receitas', ReceitasController::class);
    Route::get('receitas/detal/{id}', [ReceitasController::class, 'detal'])->name('receitas.detal');

    Route::resource('despesas', DespesasController::class);
    Route::get('despesas/detal/{id}', [DespesasController::class, 'detal'])->name('despesas.detal');
    Route::post('despesas/relatorio', [DespesasController::class, 'relatorio'])->name('despesas.relatorio');


    Route::resource('contas-bancarias', ContaBancariaController::class);
    Route::resource('propostas', PropostasController::class);
    Route::get('propostas/invoice/{id}', [PropostasController::class, 'invoice'])->name('propostas.invoice');

    Route::resource('produtos', ProdutoController::class);

    
});

Route::group(['prefix' => 'gestao-pessoas'], function () {
    Route::get('clientes/{id}/active', [ClientesController::class, 'active'])->name('clientes.active');
    Route::resource('clientes', ClientesController::class);

    Route::get('fornecedores/{id}/active', [FornecedoresController::class, 'active'])->name('fornecedores.active');
    Route::resource('fornecedores', FornecedoresController::class);

    Route::get('leads/{id}/active', [LeadsController::class, 'active'])->name('leads.active');
    Route::resource('leads-controller', LeadsController::class);

    Route::get('usuarios/{id}/funcoes',[UserController::class, 'funcoes'])->name('usuarios.funcoes');
    Route::put('usuarios/{id}/funcoes/sync',[UserController::class, 'funcoesSync'])->name('usuarios.funcoesSync');
    Route::resource('usuarios', UserController::class);

    Route::get('funcoes/{id}/permissoes',[RoleController::class, 'permissoes'])->name('funcoes.permissoes');
    Route::put('funcoes/{id}/permissoes/sync',[RoleController::class, 'permissoesSync'])->name('funcoes.permissoesSync');
    Route::resource('funcoes', RoleController::class);

    Route::resource('permissoes', PermissionController::class);
    Route::get('leads', Leads::class);

});

Route::group(['prefix' => 'gestao-marketing'], function () {
    Route::get('consultorias/consultoria', [ConsultoriaController::class, 'consultoria'])->name('consultorias.consultoria');
    Route::post('consultorias/montar', [ConsultoriaController::class, 'montar'])->name('consultorias.montar');
    Route::resource('consultorias', ConsultoriaController::class);
    Route::resource('contratos', ContratoController::class);
    Route::resource('apresentacao', ApresentacaoController::class);

    Route::get('gestao-anuncios/{id}/relatorio', [GestaoAnuncioController::class, 'relatorio'])->name('gestao-anuncios.relatorio');
    Route::resource('gestao-anuncios', GestaoAnuncioController::class);
});

Route::group(['prefix' => 'configuracao'], function () {
    Route::resource('plataformas', PlataformaController::class);
    Route::resource('plataforma-itens', PlataformaItensController::class);
    Route::resource('planos-gestao', PlanoGestaoController::class);
});

resources/views/content/funcoes/create.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('clientes.index')}}">Funções</a></li>
                            <li class="breadcrumb-item active">Adicionar Função</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Adicionar Função</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <form action="{{ route('funcoes.store') }}" method="POST" novalidate>
            @method('POST')
            @csrf
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dados Gerais</h5>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="projectname">Nome da Função</label>
                                <input type="text"  name="name" class="form-control"  style="text-transform: capitalize;" placeholder="Nome da função" value="{{old('name')}}" required>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="row">
                            <div class="col-6">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-xl-2">
                                            <div class="form-group">
                                                <a class="btn btn-danger" href="{{ URL::previous()}}">
                                                        Cancelar<span class="badge badge-primary"></span>
                                                </a>
                                            </div>
                                        </div> <!-- end col-->
                                        <div class="col-xl-2 ml-3">
                                                <div class="form-group">
                                                    <button class="btn btn-primary" type="submit">
                                                            Adicionar<span class="badge badge-primary"></span>
                                                    </button>
                                                </div>
                                            </div> <!-- end col-->
                                    </div>
                                </div> <!-- end card-body -->
                            </div>
                        </div>
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>

        </form>
    </div> <!-- container -->

@endsection

@section('js')
    <script>
        $('select[name="tipo"]').change( function() {
            if($('select[name="tipo"]').val() === 'pf'){
                $('.juridica').addClass('d-none');
                $('.fisica').removeClass('d-none');
            } else{
                $('.fisica').addClass('d-none');
                $('.juridica').removeClass('d-none');
            }
        })
    </script>
@endsection

resources/views/content/funcoes/edit.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('clientes.index')}}">Funções</a></li>
                            <li class="breadcrumb-item active">Editar Função</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Editar Função</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <form action="{{ route('funcoes.update', $record->id) }}" method="POST" novalidate>
            @method('PUT')
            @csrf
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dados Gerais</h5>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="projectname">Nome da Função</label>
                                <input type="text"  name="name" class="form-control"  style="text-transform: capitalize;" placeholder="Nome da função" value="{{old('name') ?? $record->name}}" required>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="row">
                            <div class="col-6">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-xl-2">
                                            <div class="form-group">
                                                <a class="btn btn-danger" href="{{ URL::previous()}}">
                                                        Cancelar<span class="badge badge-primary"></span>
                                                </a>
                                            </div>
                                        </div> <!-- end col-->
                                        <div class="col-xl-2 ml-3">
                                                <div class="form-group">
                                                    <button class="btn btn-primary" type="submit">
                                                            Atualizar<span class="badge badge-primary"></span>
                                                    </button>
                                                </div>
                                            </div> <!-- end col-->
                                    </div>
                                </div> <!-- end card-body -->
                            </div>
                        </div>
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>

        </form>
    </div> <!-- container -->

@endsection

resources/views/content/funcoes/index.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Funções</a></li>
                            <li class="breadcrumb-item active">Listar Funções</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Listar Funções</h4>
                </div>
            </div>
        </div>
       
      <!-- end page title -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <a href="{{ route('funcoes.create') }}" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle mr-2"></i> Adicionar Função</a>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-right">
                                    <button type="button" class="btn btn-success mb-2 mr-1"><i class="mdi mdi-settings"></i></button>
                                    <button type="button" class="btn btn-light mb-2 mr-1">Importar</button>
                                    <button type="button" class="btn btn-light mb-2">Exportar</button>
                                </div>
                            </div><!-- end col-->
                        </div>

                        <div class="table-responsive">
                             @if ($message = Session::get('success'))
                                @if ($message == 'store')
                                    <script>
                                        var message = 'store';
                                    </script>
                                @endif
                                @if ($message == 'update')
                                    <script>
                                        var message = 'update';
                                    </script>
                                @endif

                                @if ($message == 'destroy')
                                    <script>
                                        var message = 'destroy';
                                    </script>
                                @endif

                                @if ($message == 'active')
                                    <script>
                                        var message = 'active';
                                    </script>
                                @endif
                                
                            @endif
                         
                            <table class="table table-centered w-100 dt-responsive " id="clientes-datatable">
                                <thead class="thead-light">
                                    <tr>
                                        <th class="all">#</th>
                                        <th class="all">Funções</th>
                                        <th style="width: 100px;">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($records as $key=>$item)
                                        <tr>
                                            <td>
                                                <p class="m-0 d-inline-block align-middle font-12">
                                                    <a class="text-body"style="text-transform: uppercase;">{{ $item->id}}</a>
                                                </p>
                                            </td>
                                            <td>
                                                <p class="m-0 d-inline-block align-middle font-12">
                                                    <a class="text-body"style="text-transform: uppercase;">{{ $item->name}}</a>
                                                </p>
                                            </td>
                                            
                                            <td class="d-flex">
                                                <a class="mr-3 btn btn-sm btn-outline-success" href="{{route('funcoes.edit', $item->id)}}">Editar</a>
                                                <a class="mr-3 btn btn-sm btn-outline-info" href="{{route('funcoes.permissoes', $item->id)}}">Permissões</a>
                                                <form action="{{route('funcoes.destroy', ['funco' => $item->id])}}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <input class="btn btn-sm btn-outline-danger" type="submit" value="Remover">
                                                </form>

                                            </td>
                                        </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container -->
@endsection
@section('css') 
@stop
@section('js')
    <!-- DataTables -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        $(document).ready(function() {
          
            $('#clientes-datatable').DataTable({
                language: {
                    processing:     "Processamento...",
                    search:         "Pesquisar&nbsp;:",
                    lengthMenu:    "Mostrar _MENU_ entradas",
                    info:           "Exibindo _START_ até _END_ de _TOTAL_ entradas",
                    infoEmpty:      "Exibindo da entrada 0 até 0 de 0 entradas",
                    infoFiltered:   "(filtro total de _MAX_ entradas)",
                    infoPostFix:    "",
                    loadingRecords: "Carregando ...",
                    zeroRecords:    "Nenhuma entrada encontrada",
                    emptyTable:     "Nenhuma entrada disponível na tabela",
                    paginate: {
                        first:      "Primeiro",
                        previous:   "Anterior",
                        next:       "Ultimo",
                        last:       "Depos"
                    },
                    aria: {
                        sortAscending:  ": ativar para classificar a coluna em ordem crescente",
                        sortDescending: ": ativar para classificar a coluna em ordem decrescente"
                    }
                }
            });
        } );
    </script>
    <script type="text/javascript">
    
        if(message == 'store'){
            Swal.fire(
                'Parabéns!',
                'Registro cadastrado com sucesso!',
                'success'
            )
        }
        if(message == 'update'){
            Swal.fire(
                'Parabéns!',
                'Registro editado com sucesso!',
                'success'
            )
        }   
        
        if(message == 'destroy'){
            Swal.fire(
                'Alerta!',
                'Registro inativado com sucesso!',
                'info'
            )
        } 

        if(message == 'active'){
            Swal.fire(
                'Alerta!',
                'Registro ativado com sucesso!',
                'info'
            )
        }   
        
    </script> 

@stop

resources/views/content/funcoes/permissoes.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('funcoes.index') }}">Funções</a></li>
                            <li class="breadcrumb-item active">Adicionar Permissão</li>
                        </ol>
                    </div>
                    <h3 class="page-title">Adicionar Permissão</h3>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <form action="{{ route('funcoes.permissoesSync', $funcao->id) }}" method="POST" novalidate>
            @method('PUT')
            @csrf
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Permissões para: {{ $funcao->name }}</h4>
                                    @foreach ($permissoes as $key => $permissao)
                                            <div class="col-6">
                                                <div class="custom-control custom-checkbox">
                                                    <p class="m-0 d-inline-block align-middle font-16">
                                                        <input type="checkbox" class="custom-control-input"
                                                            name="{{ $permissao->id }}" id="{{ $permissao->id }}"
                                                            {{ $permissao->can == 1 ? 'checked' : '' }}>
                                                        <label class="custom-control-label"
                                                            for="{{ $permissao->id }}">{{ $permissao->name }}</label>
                                                    </p>
                                                </div>
                                            </div>
                                    @endforeach

                            <div class="row mt-2">
                                <div class="col-xl-1">
                                    <div class="form-group">
                                        <a class="btn btn-danger" href="{{ URL::previous() }}">
                                            Cancelar<span class="badge badge-primary"></span>
                                        </a>
                                    </div>
                                </div> <!-- end col-->
                                <div class="col-xl-1 ml-2">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">
                                            Sincronizar<span class="badge badge-primary"></span>
                                        </button>
                                    </div>
                                </div> <!-- end col-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div> <!-- container -->

@endsection

@section('js')
    <!-- DataTables -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        $(document).ready(function() {

            $('#permissoes-datatable').DataTable({
                language: {
                    processing: "Processamento...",
                    search: "Pesquisar&nbsp;:",
                    lengthMenu: "Mostrar _MENU_ entradas",
                    info: "Exibindo _START_ até _END_ de _TOTAL_ entradas",
                    infoEmpty: "Exibindo da entrada 0 até 0 de 0 entradas",
                    infoFiltered: "(filtro total de _MAX_ entradas)",
                    infoPostFix: "",
                    loadingRecords: "Carregando ...",
                    zeroRecords: "Nenhuma entrada encontrada",
                    emptyTable: "Nenhuma entrada disponível na tabela",
                    paginate: {
                        first: "Primeiro",
                        previous: "Anterior",
                        next: "Ultimo",
                        last: "Depos"
                    },
                    aria: {
                        sortAscending: ": ativar para classificar a coluna em ordem crescente",
                        sortDescending: ": ativar para classificar a coluna em ordem decrescente"
                    }
                }
            });
        });
    </script>
    <script type="text/javascript">
        if (message == 'store') {
            Swal.fire(
                'Parabéns!',
                'Registro cadastrado com sucesso!',
                'success'
            )
        }
        if (message == 'update') {
            Swal.fire(
                'Parabéns!',
                'Registro editado com sucesso!',
                'success'
            )
        }

        if (message == 'destroy') {
            Swal.fire(
                'Alerta!',
                'Registro inativado com sucesso!',
                'info'
            )
        }

        if (message == 'active') {
            Swal.fire(
                'Alerta!',
                'Registro ativado com sucesso!',
                'info'
            )
        }
    </script>

@stop