routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\CustoController;
use App\Http\Controllers\SalarioController;
use App\Http\Controllers\PlanosController;
use App\Http\Controllers\ServicoAgenciadoController;
use App\Http\Controllers\BaseCustoController;
use App\Http\Controllers\CadastroDiversosFinancController;
use App\Http\Controllers\ContaController;
use App\Http\Controllers\CentroCustoController;
use App\Http\Controllers\CategoriaLancController;
use App\Http\Controllers\SubCategoriaLancController;
use App\Http\Controllers\LancamentoController;
use App\Http\Controllers\ReceitasController;
use App\Http\Controllers\DespesasController;
use App\Http\Controllers\FornecedoresController;
use App\Http\Controllers\PropostasController;
use App\Http\Controllers\LeadsController;
use App\Http\Controllers\GestaoAnuncioController;
use App\Http\Controllers\LinhaEditorialController;
use App\Http\Controllers\ProspeccaoController;
use App\Http\Controllers\ConversaController;
use App\Http\Controllers\ConsultoriaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ContratoController;
use App\Http\Controllers\ApresentacaoController;
use App\Http\Controllers\ContaBancariaController;
use App\Http\Controllers\PlataformaController;
use App\Http\Controllers\PlataformaItensController;
use App\Http\Controllers\GoogleAdsController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\PlanoGestaoController;
use App\Http\Livewire\Leads;



Auth::routes();
Route::get('/', [HomeController::class, 'index'])->name('home');



Route::group(['prefix' => 'pdf'], function () {
    Route::get('resumo/{id}', [PdfController::class, 'resumo'])->name('pdf.resumo');
    Route::get('recibo/{id}', [PdfController::class, 'recibo'])->name('pdf.recibo');
});



Route::group(['prefix' => 'gestao-financeira'], function () {
    Route::resource('custos', CustoController::class);
    Route::resource('custos-salarios', SalarioController::class);
    Route::resource('planos', PlanosController::class);
    Route::resource('servicos-agenciado', ServicoAgenciadoController::class);
    Route::resource('base-custos', BaseCustoController::class);
    Route::get('cadastros-diversos', [CadastroDiversosFinancController::class, 'index'])->name('cadastros.diversos');
    Route::resource('plano-contas', ContaController::class);
    Route::resource('centro-custos', CentroCustoController::class);
    Route::resource('categorias', CategoriaLancController::class);
    Route::resource('subcategorias', SubCategoriaLancController::class);
    Route::resource('lancamentos', LancamentoController::class);

    Route::resource('receitas', ReceitasController::class);
    Route::get('receitas/detal/{id}', [ReceitasController::class, 'detal'])->name('receitas.detal');

    Route::resource('despesas', DespesasController::class);
    Route::get('despesas/detal/{id}', [DespesasController::class, 'detal'])->name('despesas.detal');
    Route::post('despesas/relatorio', [DespesasController::class, 'relatorio'])->name('despesas.relatorio');


    Route::resource('contas-bancarias', ContaBancariaController::class);
    Route::resource('propostas', PropostasController::class);
    Route::get('propostas/invoice/{id}', [PropostasController::class, 'invoice'])->name('propostas.invoice');

    Route::resource('produtos', ProdutoController::class);

    
});

Route::group(['prefix' => 'gestao-pessoas'], function () {
    Route::get('clientes/{id}/active', [ClientesController::class, 'active'])->name('clientes.active');
    Route::resource('clientes', ClientesController::class);

    Route::get('fornecedores/{id}/active', [FornecedoresController::class, 'active'])->name('fornecedores.active');
    Route::resource('fornecedores', FornecedoresController::class);

    Route::get('leads/{id}/active', [LeadsController::class, 'active'])->name('leads.active');
    Route::resource('leads-controller', LeadsController::class);

    Route::get('usuarios/{id}/funcoes',[UserController::class, 'funcoes'])->name('usuarios.funcoes');
    Route::put('usuarios/{id}/funcoes/sync',[UserController::class, 'funcoesSync'])->name('usuarios.funcoesSync');
    Route::resource('usuarios', UserController::class);

    Route::get('funcoes/{id}/permissoes',[RoleController::class, 'permissoes'])->name('funcoes.permissoes');
    Route::put('funcoes/{id}/permissoes/sync',[RoleController::class, 'permissoesSync'])->name('funcoes.permissoesSync');
    Route::resource('funcoes', RoleController::class);

    Route::resource('permissoes', PermissionController::class);
    Route::get('leads', Leads::class);

});

Route::group(['prefix' => 'gestao-marketing'], function () {
    Route::get('consultorias/consultoria', [ConsultoriaController::class, 'consultoria'])->name('consultorias.consultoria');
    Route::post('consultorias/montar', [ConsultoriaController::class, 'montar'])->name('consultorias.montar');
    Route::resource('consultorias', ConsultoriaController::class);
    Route::resource('contratos', ContratoController::class);
    Route::resource('apresentacao', ApresentacaoController::class);

    Route::get('gestao-anuncios/{id}/relatorio', [GestaoAnuncioController::class, 'relatorio'])->name('gestao-anuncios.relatorio');
    Route::resource('gestao-anuncios', GestaoAnuncioController::class);
});

Route::group(['prefix' => 'configuracao'], function () {
    Route::resource('plataformas', PlataformaController::class);
    Route::resource('plataforma-itens', PlataformaItensController::class);
    Route::resource('planos-gestao', PlanoGestaoController::class);
});

app/Http/Controllers/PdfController.php
<?php

namespace App\Http\Controllers;

use App\Models\ItensPropostas;
use App\Models\Lancamento;
use App\Models\Lancamento_itens;
use App\Models\Pessoa;
use App\Models\Propostas;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class PdfController extends Controller
{
    public function resumo($id)
    {
        
        $proposta = Propostas::find($id);        
        $itensProposta = ItensPropostas::where('id_proposta', $id)->get();
        $cliente = Pessoa::where('rotulo', 'clientes')->first();
        $endereco = $cliente->endereco()->first();
        
        
        $total = $itensProposta->sum('valor_total') - $proposta->desconto;
        

        return view('content.pdfs.resumo', compact('proposta', 'itensProposta', 'cliente', 'endereco', 'total'));
    }
    public function recibo($id)
    {  
        
        $receita = Lancamento_itens::where('id', $id)->first();
        $lancamento = Lancamento::where('id', $receita->id_lancamento)->first();
        $empresa = Pessoa::where('id', Auth::user()->id_empresa)->first();
        $receita->valor_amoretizado_extenso = $this->valorPorExtenso($receita->valor_amoretizado, true,false);
        return view('content.pdfs.recibo', compact('receita', 'lancamento', 'empresa'));
    }

    public static function valorPorExtenso( $valor = 0, $bolExibirMoeda = true, $bolPalavraFeminina = false )
    {
 
        $singular = null;
        $plural = null;
 
        if ( $bolExibirMoeda )
        {
            $singular = array("centavo", "real", "mil", "milhão", "bilhão", "trilhão", "quatrilhão");
            $plural = array("centavos", "reais", "mil", "milhões", "bilhões", "trilhões","quatrilhões");
        }
        else
        {
            $singular = array("", "", "mil", "milhão", "bilhão", "trilhão", "quatrilhão");
            $plural = array("", "", "mil", "milhões", "bilhões", "trilhões","quatrilhões");
        }
 
        $c = array("", "cem", "duzentos", "trezentos", "quatrocentos","quinhentos", "seiscentos", "setecentos", "oitocentos", "novecentos");
        $d = array("", "dez", "vinte", "trinta", "quarenta", "cinquenta","sessenta", "setenta", "oitenta", "noventa");
        $d10 = array("dez", "onze", "doze", "treze", "quatorze", "quinze","dezesseis", "dezessete", "dezoito", "dezenove");
        $u = array("", "um", "dois", "três", "quatro", "cinco", "seis","sete", "oito", "nove");
 
 
        if ( $bolPalavraFeminina )
        {
        
            if ($valor == 1) 
            {
                $u = array("", "uma", "duas", "três", "quatro", "cinco", "seis","sete", "oito", "nove");
            }
            else 
            {
                $u = array("", "um", "duas", "três", "quatro", "cinco", "seis","sete", "oito", "nove");
            }
            
            
            $c = array("", "cem", "duzentas", "trezentas", "quatrocentas","quinhentas", "seiscentas", "setecentas", "oitocentas", "novecentas");
            
            
        }
 
 
        $z = 0;
 
        $valor = number_format( $valor, 2, ".", "." );
        $inteiro = explode( ".", $valor );
 
        for ( $i = 0; $i < count( $inteiro ); $i++ ) 
        {
            for ( $ii = mb_strlen( $inteiro[$i] ); $ii < 3; $ii++ ) 
            {
                $inteiro[$i] = "0" . $inteiro[$i];
            }
        }
 
        // $fim identifica onde que deve se dar junção de centenas por "e" ou por "," ;)
        $rt = null;
        $fim = count( $inteiro ) - ($inteiro[count( $inteiro ) - 1] > 0 ? 1 : 2);
        for ( $i = 0; $i < count( $inteiro ); $i++ )
        {
            $valor = $inteiro[$i];
            $rc = (($valor > 100) && ($valor < 200)) ? "cento" : $c[$valor[0]];
            $rd = ($valor[1] < 2) ? "" : $d[$valor[1]];
            $ru = ($valor > 0) ? (($valor[1] == 1) ? $d10[$valor[2]] : $u[$valor[2]]) : "";
 
            $r = $rc . (($rc && ($rd || $ru)) ? " e " : "") . $rd . (($rd && $ru) ? " e " : "") . $ru;
            $t = count( $inteiro ) - 1 - $i;
            $r .= $r ? " " . ($valor > 1 ? $plural[$t] : $singular[$t]) : "";
            if ( $valor == "000")
                $z++;
            elseif ( $z > 0 )
                $z--;
                
            if ( ($t == 1) && ($z > 0) && ($inteiro[0] > 0) )
                $r .= ( ($z > 1) ? " de " : "") . $plural[$t];
                
            if ( $r )
                $rt = $rt . ((($i > 0) && ($i <= $fim) && ($inteiro[0] > 0) && ($z < 1)) ? ( ($i < $fim) ? ", " : " e ") : " ") . $r;
        }
 
        $rt = mb_substr( $rt, 1 );
 
        return($rt ? trim( $rt ) : "zero");
 
    }

    public static function removerFormatacaoNumero( $strNumero )
    {
 
        $strNumero = trim( str_replace( "R$", null, $strNumero ) );
 
        $vetVirgula = explode( ",", $strNumero );
        if ( count( $vetVirgula ) == 1 )
        {
            $acentos = array(".");
            $resultado = str_replace( $acentos, "", $strNumero );
            return $resultado;
        }
        else if ( count( $vetVirgula ) != 2 )
        {
            return $strNumero;
        }
 
        $strNumero = $vetVirgula[0];
        $strDecimal = mb_substr( $vetVirgula[1], 0, 2 );
 
        $acentos = array(".");
        $resultado = str_replace( $acentos, "", $strNumero );
        $resultado = $resultado . "." . $strDecimal;
 
        return $resultado;
 
    }
}

resources/views/content/pdfs/recibo.blade.php
@extends('layouts.app')
@section('content')
 <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('receitas.index') }}">Receitas</a></li>
                            <li class="breadcrumb-item active">Recibo</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Recibo de Pagamento</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <!-- Invoice Logo-->
                        <div class="clearfix">
                            <div class="float-left mb-3">
                                <img src="{{ url('/images/logo.png') }}" alt="" height="70">
                            </div>
                            <div class="float-right">
                                <h4 class="m-0 d-print-none">RECIBO DE PAGAMENTO</h4>
                            </div>
                        </div>
                        <h2 class="text-muted text-center font-24">Recibo de Pagamento</h2>
                        <!-- Invoice Detail-->
                        <div class="row">
                            
                            <div class="col-sm-6">
                                <div class="float-left mt-3">
                                    <p class="text-muted font-13">
                                        Por meio deste documento, declaro, para todos os fins e a quem possa interessar, que recebi da pessoa {{   $lancamento->cliente->tipo == 'pf' ? 'Fisica' : 'Juridica'  }},{{ $lancamento->cliente->nome }}, portador do documento {{   $lancamento->cliente->tipo == 'pf' ? 'CPF: ' : 'CNPJ: '  }} nº: {{ $lancamento->cliente->cpf }} com sede em {{ $lancamento->cliente->endereco->localidade }}, a quantia de R$ {{ $receita->valor_amoretizado }} <b>( {{ $receita->valor_amoretizado_extenso }} )</b>, referente à seguinte situação:
                                        <p class="text-muted font-13">
                                           Pagamento da parcela {{ $receita->parcela }} de {{ $lancamento->parcela }}
                                        </p>
                                        <p class="text-muted font-13"> Por ser verdade, assino a presente.</p>
                                    </p>                                    
                                </div>

                            </div><!-- end col -->
                            <div class="col-sm-4 offset-sm-2">
                                <div class="mt-3 float-sm-right">
                                    <p class="font-13"><strong>Data Recibo: </strong> &nbsp;&nbsp;&nbsp; {{ $receita->created_at->format('d/m/Y') }}</p>
                                    <p class="font-13"><strong>ID Recibo: </strong> <span class="float-right">#{{$lancamento->id }}</span></p>
                                </div>
                            </div><!-- end col -->
                        </div>
                        <!-- end row -->

                        <div class="row mt-4">
                            <div class="col-sm-4">
                                <h6>Endereço</h6>
                                <address>
                                   {{$lancamento->cliente->endereco->logradouro}},{{$lancamento->cliente->endereco->numero }} {{ $lancamento->cliente->endereco->complemento }}<br>                                    
                                     {{ $lancamento->cliente->endereco->bairro }}<br>                                    
                                   {{ $lancamento->cliente->endereco->localidade }},{{ $lancamento->cliente->endereco->uf }} &nbsp; {{$lancamento->cliente->endereco->cep }}  <br>                                   
                                    <abbr title="Phone">Celular:</abbr>                                    
                                    {{ $lancamento->cliente->celular }}
                                    
                                </address>
                            </div> <!-- end col-->
                        </div>    
                        <!-- end row -->        

                        <div class="row">
                            <div class="col-sm-7 mt-5">
                                ____________________________________________________________________________________<br>
                                <h3>{{ $empresa->nome }} -- {{   $empresa->tipo == 'pf' ? 'CPF: ' : 'CNPJ: '  }} nº: {{ $empresa->cpf }} </h3> 
                               {{--  <div class="clearfix pt-3">
                                    <h6 class="text-muted">Notas:</h6>
                                    <small>
                                        Todas as contas devem ser pagas dentro de 7 dias após o recebimento da fatura. Se a conta não for paga dentro de 7 dias, os serviços poderá ser suspenso sem
                                        aviso previo.
                                    </small>
                                </div> --}}
                            </div> <!-- end col -->
                            
                        </div>
                        <!-- end row-->

                        <div class="d-print-none mt-4">
                            <div class="text-right">
                                <a href="javascript:window.print()" class="btn btn-primary imprimir"><i class="mdi mdi-printer"></i> Imprimir</a>
                                <a href="{{ route('receitas.index') }}" class="btn btn-info">Fechar</a>
                            </div>
                        </div>   
                        <!-- end buttons -->

                    </div> <!-- end card-body-->
                </div> <!-- end card -->
            </div> <!-- end col-->
        </div>
        <!-- end row -->
        <hr>
        <div class="row mt-5 recibo d-none">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <!-- Invoice Logo-->
                        <div class="clearfix">
                            <div class="float-left mb-3">
                                <img src="{{ url('/images/logo.png') }}" alt="" height="70">
                            </div>
                            <div class="float-right">
                                <h4 class="m-0 d-print-none">RECIBO DE PAGAMENTO</h4>
                            </div>
                        </div>
                        <h2 class="text-muted text-center font-24">Recibo de Pagamento</h2>
                        <!-- Invoice Detail-->
                        <div class="row">
                            
                            <div class="col-sm-6">
                                <div class="float-left mt-3">
                                    <p class="text-muted font-13">
                                        Por meio deste documento, declaro, para todos os fins e a quem possa interessar, que recebi da pessoa {{   $lancamento->cliente->tipo == 'pf' ? 'Fisica' : 'Juridica'  }},{{ $lancamento->cliente->nome }}, portador do documento {{   $lancamento->cliente->tipo == 'pf' ? 'CPF: ' : 'CNPJ: '  }} nº: {{ $lancamento->cliente->cpf }} com sede em {{ $lancamento->cliente->endereco->localidade }}, a quantia de R$ {{ $receita->valor_amoretizado }} <b>( {{ $receita->valor_amoretizado_extenso }} )</b>, referente à seguinte situação:
                                        <p class="text-muted font-13">
                                           Pagamento da parcela {{ $receita->parcela }} de {{ $lancamento->parcela }}
                                        </p>
                                        <p class="text-muted font-13"> Por ser verdade, assino a presente.</p>
                                    </p>                                    
                                </div>

                            </div><!-- end col -->
                            <div class="col-sm-4 offset-sm-2">
                                <div class="mt-3 float-sm-right">
                                    <p class="font-13"><strong>Data Recibo: </strong> &nbsp;&nbsp;&nbsp; {{ $receita->created_at->format('d/m/Y') }}</p>
                                    <p class="font-13"><strong>ID Recibo: </strong> <span class="float-right">#{{$lancamento->id }}</span></p>
                                </div>
                            </div><!-- end col -->
                        </div>
                        <!-- end row -->

                        <div class="row mt-4">
                            <div class="col-sm-4">
                                <h6>Endereço</h6>
                                <address>
                                   {{$lancamento->cliente->endereco->logradouro}},{{$lancamento->cliente->endereco->numero }} {{ $lancamento->cliente->endereco->complemento }}<br>                                    
                                     {{ $lancamento->cliente->endereco->bairro }}<br>                                    
                                   {{ $lancamento->cliente->endereco->localidade }},{{ $lancamento->cliente->endereco->uf }} &nbsp; {{$lancamento->cliente->endereco->cep }}  <br>                                   
                                    <abbr title="Phone">Celular:</abbr>                                    
                                    {{ $lancamento->cliente->celular }}
                                    
                                </address>
                            </div> <!-- end col-->
                        </div>    
                        <!-- end row -->        

                        <div class="row">
                            <div class="col-sm-7 mt-5">
                                ____________________________________________________________________________________<br>
                                <h3>{{ $empresa->nome }} -- {{   $empresa->tipo == 'pf' ? 'CPF: ' : 'CNPJ: '  }} nº: {{ $empresa->cpf }} </h3> 
                               {{--  <div class="clearfix pt-3">
                                    <h6 class="text-muted">Notas:</h6>
                                    <small>
                                        Todas as contas devem ser pagas dentro de 7 dias após o recebimento da fatura. Se a conta não for paga dentro de 7 dias, os serviços poderá ser suspenso sem
                                        aviso previo.
                                    </small>
                                </div> --}}
                            </div> <!-- end col -->
                            
                        </div>
                        <!-- end row-->

                    </div> <!-- end card-body-->
                </div> <!-- end card -->
            </div> <!-- end col-->
        </div>
        <!-- end row -->
        
    </div> <!-- container -->
@endsection
@section('js')

<script>
    $('.imprimir').click( function() {
        $('.recibo').removeClass('d-none');
        setInterval(function(){
            $('.recibo').addClass('d-none');
            }, 3000);
    });
</script>
    
@endsection

resources/views/content/pdfs/relatorio.blade.php
@extends('layouts.app')
@section('content')
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Despesas</a></li>
                            <li class="breadcrumb-item active">Relatório</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Relatórior</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="container">
                        <div class="card-body">

                            <!-- Invoice Logo-->
                            <div class="clearfix">
                                <div class="float-left mb-3">
                                    <img src="https://agenciamms.com.br/wp-content/uploads/2021/01/Logo-transparente.png"
                                        alt="" height="100">
                                </div>
                                <div class="float-right">
                                    <h4 class="m-0 d-print-none">RELATÓRIO DE DESPESAS
                                    </h4>
                                </div>
                            </div>

                            <!-- Invoice Detail-->
                            <div class="row">
                                <div class="col-sm-6">
                                   

                                </div><!-- end col -->
                                <div class="col-sm-4 offset-sm-2">
                                    
                                </div><!-- end col -->
                            </div>
                            <!-- end row -->

                            
                            <div class="row pt-3" style="page-break-inside:avoid">

                                <div class="col-md-12 text-left">
                                    <h4><b>Despesas do mês DE  {{$mes}}</b></h4>
                                    <h5>Total das despesas: <b>R$ {{$total_divida_mes}}</b></h5>
                                    <div class="table-responsive">
                                        <table class="table mt-4">
                                            <thead>
                                                <tr>
                                                    <th>#Descrição</th>
                                                    <th>Total Parcelas</th>
                                                    <th>Total Lançamentos</th>
                                                    <th>Valor Unit</th>
                                                    <th>Data Venc</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($despesas as $key => $item)
                                                    <tr>
                                                        <td>{{ $item->descricao}}</td>
                                                        <td>
                                                            <b>{{ $item->parcela }} parcelas</b>
                                                        </td>

                                                        <td> R$  {{ $item->valor_lancamento }}</td>
                                                        <td>
                                                            @foreach ($item->itens as $lanc)
                                                            <a class="text-body"> Parcela: {{$lanc->parcela}}</a>
                                                            <br/>
                                                            <a class="text-body">R$ {{$lanc->valor_parcela}}</a>
                                                            @endforeach
                                                        </td>

                                                        <td>  
                                                            @foreach ($item->itens as $lanc)
                                                                <a class="text-body">{{date('d/m/Y', strtotime($lanc->data_pagto))}}</a>
                                                            @endforeach</td>
                                                    </tr>
                                                @endforeach

                                            </tbody>
                                        </table>
                                    </div> <!-- end table-responsive-->
                                </div>
                            </div>

                            <div class="row pt-5"></div>

                            
                            <div class="d-print-none mt-4" style="page-break-inside:avoid">
                                <div class="text-right">
                                    <a href="javascript:window.print()" class="btn btn-primary"><i
                                            class="mdi mdi-printer"></i> Imprimir</a>
                                    <a href="{{ route('despesas.index') }}" class="btn btn-info">Fechar</a>
                                   
                                </div>
                            </div>
                            <!-- end buttons -->

                        </div> <!-- end card-body-->
                    </div>
                </div> <!-- end card -->
            </div> <!-- end col-->
        </div>
        <!-- end row -->

    </div> <!-- container -->

@endsection

resources/views/content/pdfs/relatorio_mkt.blade.php
@extends('layouts.app')
@section('content')
 <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('gestao-anuncios.index') }}">Receitas</a></li>
                            <li class="breadcrumb-item active">Recibo</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Recibo de Pagamento</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <!-- Invoice Logo-->
                        <div class="clearfix">
                            <div class="float-right mb-3">
                                <img src="{{ url('https://agenciamms.com/wp-content/uploads/2021/11/cropped-logo.png') }}" alt="" height="70">
                            </div>
                            <div class="float-left">
                                <h1 class="m-5" style="width: 300px">{{$record->cliente->nome}}</h1>
                            </div>
                        </div>
                        <h2 class="text-muted text-center font-24">Recibo de Pagamento</h2>
                       
                            

                        <div class="d-print-none mt-4">
                            <div class="text-right">
                                <a href="javascript:window.print()" class="btn btn-primary imprimir"><i class="mdi mdi-printer"></i> Imprimir</a>
                                <a href="{{ route('gestao-anuncios.index') }}" class="btn btn-info">Fechar</a>
                            </div>
                        </div>   
                        <!-- end buttons -->

                    </div> <!-- end card-body-->
                </div> <!-- end card -->
            </div> <!-- end col-->
        </div>
        <!-- end row -->
        
    </div> <!-- container -->
@endsection
@section('js')

<script>
    $('.imprimir').click( function() {
        $('.recibo').removeClass('d-none');
        setInterval(function(){
            $('.recibo').addClass('d-none');
            }, 3000);
    });
</script>
    
@endsection