routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\CustoController;
use App\Http\Controllers\SalarioController;
use App\Http\Controllers\PlanosController;
use App\Http\Controllers\ServicoAgenciadoController;
use App\Http\Controllers\BaseCustoController;
use App\Http\Controllers\CadastroDiversosFinancController;
use App\Http\Controllers\ContaController;
use App\Http\Controllers\CentroCustoController;
use App\Http\Controllers\CategoriaLancController;
use App\Http\Controllers\SubCategoriaLancController;
use App\Http\Controllers\LancamentoController;
use App\Http\Controllers\ReceitasController;
use App\Http\Controllers\DespesasController;
use App\Http\Controllers\FornecedoresController;
use App\Http\Controllers\PropostasController;
use App\Http\Controllers\LeadsController;
use App\Http\Controllers\GestaoAnuncioController;
use App\Http\Controllers\LinhaEditorialController;
use App\Http\Controllers\ProspeccaoController;
use App\Http\Controllers\ConversaController;
use App\Http\Controllers\ConsultoriaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ContratoController;
use App\Http\Controllers\ApresentacaoController;
use App\Http\Controllers\ContaBancariaController;
use App\Http\Controllers\PlataformaController;
use App\Http\Controllers\PlataformaItensController;
use App\Http\Controllers\GoogleAdsController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\PlanoGestaoController;
use App\Http\Livewire\Leads;



Auth::routes();
Route::get('/', [HomeController::class, 'index'])->name('home');



Route::group(['prefix' => 'pdf'], function () {
    Route::get('resumo/{id}', [PdfController::class, 'resumo'])->name('pdf.resumo');
    Route::get('recibo/{id}', [PdfController::class, 'recibo'])->name('pdf.recibo');
});



Route::group(['prefix' => 'gestao-financeira'], function () {
    Route::resource('custos', CustoController::class);
    Route::resource('custos-salarios', SalarioController::class);
    Route::resource('planos', PlanosController::class);
    Route::resource('servicos-agenciado', ServicoAgenciadoController::class);
    Route::resource('base-custos', BaseCustoController::class);
    Route::get('cadastros-diversos', [CadastroDiversosFinancController::class, 'index'])->name('cadastros.diversos');
    Route::resource('plano-contas', ContaController::class);
    Route::resource('centro-custos', CentroCustoController::class);
    Route::resource('categorias', CategoriaLancController::class);
    Route::resource('subcategorias', SubCategoriaLancController::class);
    Route::resource('lancamentos', LancamentoController::class);

    Route::resource('receitas', ReceitasController::class);
    Route::get('receitas/detal/{id}', [ReceitasController::class, 'detal'])->name('receitas.detal');

    Route::resource('despesas', DespesasController::class);
    Route::get('despesas/detal/{id}', [DespesasController::class, 'detal'])->name('despesas.detal');
    Route::post('despesas/relatorio', [DespesasController::class, 'relatorio'])->name('despesas.relatorio');


    Route::resource('contas-bancarias', ContaBancariaController::class);
    Route::resource('propostas', PropostasController::class);
    Route::get('propostas/invoice/{id}', [PropostasController::class, 'invoice'])->name('propostas.invoice');

    Route::resource('produtos', ProdutoController::class);

    
});

Route::group(['prefix' => 'gestao-pessoas'], function () {
    Route::get('clientes/{id}/active', [ClientesController::class, 'active'])->name('clientes.active');
    Route::resource('clientes', ClientesController::class);

    Route::get('fornecedores/{id}/active', [FornecedoresController::class, 'active'])->name('fornecedores.active');
    Route::resource('fornecedores', FornecedoresController::class);

    Route::get('leads/{id}/active', [LeadsController::class, 'active'])->name('leads.active');
    Route::resource('leads-controller', LeadsController::class);

    Route::get('usuarios/{id}/funcoes',[UserController::class, 'funcoes'])->name('usuarios.funcoes');
    Route::put('usuarios/{id}/funcoes/sync',[UserController::class, 'funcoesSync'])->name('usuarios.funcoesSync');
    Route::resource('usuarios', UserController::class);

    Route::get('funcoes/{id}/permissoes',[RoleController::class, 'permissoes'])->name('funcoes.permissoes');
    Route::put('funcoes/{id}/permissoes/sync',[RoleController::class, 'permissoesSync'])->name('funcoes.permissoesSync');
    Route::resource('funcoes', RoleController::class);

    Route::resource('permissoes', PermissionController::class);
    Route::get('leads', Leads::class);

});

Route::group(['prefix' => 'gestao-marketing'], function () {
    Route::get('consultorias/consultoria', [ConsultoriaController::class, 'consultoria'])->name('consultorias.consultoria');
    Route::post('consultorias/montar', [ConsultoriaController::class, 'montar'])->name('consultorias.montar');
    Route::resource('consultorias', ConsultoriaController::class);
    Route::resource('contratos', ContratoController::class);
    Route::resource('apresentacao', ApresentacaoController::class);

    Route::get('gestao-anuncios/{id}/relatorio', [GestaoAnuncioController::class, 'relatorio'])->name('gestao-anuncios.relatorio');
    Route::resource('gestao-anuncios', GestaoAnuncioController::class);
});

Route::group(['prefix' => 'configuracao'], function () {
    Route::resource('plataformas', PlataformaController::class);
    Route::resource('plataforma-itens', PlataformaItensController::class);
    Route::resource('planos-gestao', PlanoGestaoController::class);
});

app/Http/Controllers/DespesasController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoriaLanc;
use App\Models\CentroCusto;
use App\Models\Conta;
use App\Models\Lancamento;
use App\Models\Lancamento_itens;
use App\Models\Pessoa;
use App\Models\SubCategoriaLanc;
use App\Models\ContaBancaria;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

use Carbon\Carbon;


class DespesasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hoje = date('Y-m-d H:m:s');
        $despesas = Lancamento::where('id_empresa',Auth::user()->id_empresa)->where('tipo', 'Despesa')->where('status', 'ativo')->get();
        $id_clientes = collect([]);
        $listClientes = collect([]);
        $allClientes = Pessoa::where('id_empresa',Auth::user()->id_empresa)->get();
        $clientes = collect([]);
        
        foreach ($despesas as $key => $despesa) {

            $listClientes->push($despesa->id_cli);
            $itensDespesa = Lancamento_itens::where('id_lancamento',$despesa->id)->get();

            foreach ($itensDespesa as $key => $value) {
                if($value->data_pagto < $hoje && $value->status != "Pago"){
                    $despesa['status_parc'] = 'Vencida';
                }
            }

            $status = Pessoa::where('id',$despesa->id_cli)->first()->status;
            $despesa->status = $status;

            
        }
        $id_clientes = $listClientes->unique();

        foreach ($allClientes as $key => $value) {
           foreach ($id_clientes as $key => $id) {
               if($id == $value->id){
                $clientes->push($value);
               }
           }
        }

       
        return view('content.financeiros.despesas.index', compact('despesas', 'clientes'));
    }
    
     public function detal($id)
    {
        $parcelas = Lancamento::where('id',$id)->first()->parcela;
        $descricao = Lancamento::where('id',$id)->first()->descricao;

        $pessoas = Pessoa::where('id',Lancamento::where('id',$id)->first()->id_cli)->first();
        $telefone = "55".Str::replace(array("(" , ")", "-", " "), '', $pessoas->celular);
        $cliente = $pessoas->fantasia;
        $despesas = Lancamento_itens::where('id_lancamento',$id)->get();
        $hoje = date('Y-m-d H:m:s');

        return view('content.financeiros.despesas.detal', compact('despesas', 'parcelas', 'descricao', 'telefone', 'cliente', 'hoje', 'id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $pessoas = Pessoa::where('id_empresa',Auth::user()->id_empresa)
        ->where(function ($query) {
            $query->where('rotulo', 'clientes')
                  ->orWhere('rotulo', 'fornecedores');
        })
        ->get();
        $lancamentos = Lancamento::where('id_empresa',Auth::user()->id_empresa)->where('tipo','Despesa')->get();
        $centro_custos = CentroCusto::where('id_empresa',Auth::user()->id_empresa)->get();
        $contas = Conta::where('id_empresa',Auth::user()->id_empresa)->get();
        $categorias = CategoriaLanc::where('id_empresa',Auth::user()->id_empresa)->get();
        $subcategorias = SubCategoriaLanc::where('id_empresa',Auth::user()->id_empresa)->get();

        return view('content.financeiros.despesas.create', compact('lancamentos', 'centro_custos','contas', 'categorias','subcategorias', 'pessoas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $bancos = collect([
            ['id' => '000', 'nome' => 'Caixa da Empresa'],
            ['id' => '001', 'nome' => 'Banco do Brasil'],
            ['id' => '003', 'nome' => 'Banco da Amazônia'],
            ['id' => '004', 'nome' => 'Banco do Nordeste'],
            ['id' => '021', 'nome' => 'Banestes'],
            ['id' => '025', 'nome' => 'Banco Alfa'],
            ['id' => '027', 'nome' => 'Besc'],
            ['id' => '029', 'nome' => 'Banerj'],
            ['id' => '031', 'nome' => 'Banco Beg'],
            ['id' => '033', 'nome' => 'Banco Santander Banespa'],
            ['id' => '036', 'nome' => 'Banco Bem'],
            ['id' => '037', 'nome' => 'Banpará'],
            ['id' => '038', 'nome' => 'Banestado'],
            ['id' => '039', 'nome' => 'BEP'],
            ['id' => '040', 'nome' => 'Banco Cargill'],
            ['id' => '041', 'nome' => 'Banrisul'],
            ['id' => '044', 'nome' => 'BVA'],
            ['id' => '045', 'nome' => 'Banco Opportunity'],
            ['id' => '047', 'nome' => 'Banese'],
            ['id' => '062', 'nome' => 'Hipercard'],
            ['id' => '063', 'nome' => 'Ibibank'],
            ['id' => '065', 'nome' => 'Lemon Bank'],
            ['id' => '066', 'nome' => 'Banco Morgan Stanley Dean Witter'],
            ['id' => '069', 'nome' => 'BPN Brasil'],
            ['id' => '070', 'nome' => 'Banco de Brasília – BRB'],
            ['id' => '072', 'nome' => 'Banco Rural'],
            ['id' => '073', 'nome' => 'Banco Popular'],
            ['id' => '074', 'nome' => 'Banco J. Safra'],
            ['id' => '075', 'nome' => 'Banco CR2'],
            ['id' => '076', 'nome' => 'Banco KDB'],
            ['id' => '077', 'nome' => 'Banco Inter'],
            ['id' => '096', 'nome' => 'Banco BMF'],
            ['id' => '104', 'nome' => 'Caixa Econômica Federal'],
            ['id' => '107', 'nome' => 'Banco BBM'],
            ['id' => '116', 'nome' => 'Banco Único'],
            ['id' => '151', 'nome' => 'Nossa Caixa'],
            ['id' => '175', 'nome' => 'Banco Finasa'],
            ['id' => '184', 'nome' => 'Banco Itaú BBA'],
            ['id' => '204', 'nome' => 'American Express Bank'],
            ['id' => '208', 'nome' => 'Banco Pactual'],
            ['id' => '212', 'nome' => 'Banco Matone'],
            ['id' => '213', 'nome' => 'Banco Arbi'],
            ['id' => '214', 'nome' => 'Banco Dibens'],
            ['id' => '217', 'nome' => 'Banco Joh Deere'],
            ['id' => '218', 'nome' => 'Banco Bonsucesso'],
            ['id' => '222', 'nome' => 'Banco Calyon Brasil'],
            ['id' => '224', 'nome' => 'Banco Fibra'],
            ['id' => '225', 'nome' => 'Banco Brascan'],
            ['id' => '229', 'nome' => 'Banco Cruzeiro'],
            ['id' => '230', 'nome' => 'Unicard'],
            ['id' => '233', 'nome' => 'Banco GE Capital'],
            ['id' => '237', 'nome' => 'Bradesco'],
            ['id' => '241', 'nome' => 'Banco Clássico'],
            ['id' => '243', 'nome' => 'Banco Stock Máxima'],
            ['id' => '246', 'nome' => 'Banco ABC Brasil'],
            ['id' => '248', 'nome' => 'Banco Boavista Interatlântico'],
            ['id' => '249', 'nome' => 'Investcred Unibanco'],
            ['id' => '250', 'nome' => 'Banco Schahin'],
            ['id' => '252', 'nome' => 'Fininvest'],
            ['id' => '254', 'nome' => 'Paraná Banco'],
            ['id' => '263', 'nome' => 'Banco Cacique'],
            ['id' => '265', 'nome' => 'Banco Fator'],
            ['id' => '266', 'nome' => 'Banco Cédula'],
            ['id' => '300', 'nome' => 'Banco de la Nación Argentina'],
            ['id' => '318', 'nome' => 'Banco BMG'],
            ['id' => '320', 'nome' => 'Banco Industrial e Comercial'],
            ['id' => '356', 'nome' => 'ABN Amro Real'],
            ['id' => '341', 'nome' => 'Itau'],
            ['id' => '347', 'nome' => 'Sudameris'],
            ['id' => '351', 'nome' => 'Banco Santander'],
            ['id' => '353', 'nome' => 'Banco Santander Brasil'],
            ['id' => '366', 'nome' => 'Banco Societe Generale Brasil'],
            ['id' => '370', 'nome' => 'Banco WestLB'],
            ['id' => '376', 'nome' => 'JP Morgan'],
            ['id' => '389', 'nome' => 'Banco Mercantil do Brasil'],
            ['id' => '394', 'nome' => 'Banco Mercantil de Crédito'],
            ['id' => '399', 'nome' => 'HSBC'],
            ['id' => '403', 'nome' => 'Banco Cora'],
            ['id' => '409', 'nome' => 'Unibanco'],
            ['id' => '412', 'nome' => 'Banco Capital'],
            ['id' => '422', 'nome' => 'Banco Safra'],
            ['id' => '453', 'nome' => 'Banco Rural'],
            ['id' => '456', 'nome' => 'Banco Tokyo Mitsubishi UFJ'],
            ['id' => '464', 'nome' => 'Banco Sumitomo Mitsui Brasileiro'],
            ['id' => '477', 'nome' => 'Citibank'],
            ['id' => '479', 'nome' => 'Itaubank (antigo Bank Boston)'],
            ['id' => '487', 'nome' => 'Deutsche Bank'],
            ['id' => '488', 'nome' => 'Banco Morgan Guaranty'],
            ['id' => '492', 'nome' => 'Banco NMB Postbank'],
            ['id' => '494', 'nome' => 'Banco la República Oriental del Uruguay'],
            ['id' => '495', 'nome' => 'Banco La Provincia de Buenos Aires'],
            ['id' => '505', 'nome' => 'Banco Credit Suisse'],
            ['id' => '600', 'nome' => 'Banco Luso Brasileiro'],
            ['id' => '604', 'nome' => 'Banco Industrial'],
            ['id' => '610', 'nome' => 'Banco VR'],
            ['id' => '611', 'nome' => 'Banco Paulista'],
            ['id' => '612', 'nome' => 'Banco Guanabara'],
            ['id' => '613', 'nome' => 'Banco Pecunia'],
            ['id' => '623', 'nome' => 'Banco Panamericano'],
            ['id' => '626', 'nome' => 'Banco Ficsa'],
            ['id' => '630', 'nome' => 'Banco Intercap'],
            ['id' => '633', 'nome' => 'Banco Rendimento'],
            ['id' => '634', 'nome' => 'Banco Triângulo'],
            ['id' => '637', 'nome' => 'Banco Sofisa'],

resources/views/content/financeiros/despesas/create.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('despesas.index')}}">Despesa</a></li>
                            <li class="breadcrumb-item active">Adicionar Despesa</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Adicionar Despesa</h4>
                </div>
            </div>
        </div>
       <div class="card">

            <div class="card-body">
                <form class="p-2" method="POST" action="{{ route('lancamentos.store') }}">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Nome </label>
                            <select class="form-control select2" data-toggle="select2" name="id_cli" required >
                                <option value="">Selecione ....</option>
                                @foreach ($pessoas as $item)
                                <option value="{{ $item->id}} " style="text-transform: uppercase;" >{{$item->tipo ==  'pj'?$item->fantasia : $item->nome}} -- {{ $item->cpf }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Tipo</label>
                            <input class="form-control form-control-light" name="tipo" value="Despesa" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Plano de Conta</label>
                            <select class="form-control select2" data-toggle="select2" name="id_plano_contas" required>
                                <option value="">Selecione ....</option>
                                @foreach ($contas as $item)
                                <option value="{{ $item->id}}" style="text-transform: capitalize;" {{$item->nome == "Empresa" ? 'selected' : ''}} >{{$item->nome}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Centro de Custo</label>
                            <select class="form-control select2" data-toggle="select2" name="id_centro_custo" required >
                                <option value="">Selecione ....</option>
                                @foreach ($centro_custos as $item)
                                <option value="{{ $item->id}} " style="text-transform: capitalize;"  {{$item->nome == "Operacional" ? 'selected' : ''}}>{{$item->nome}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Categoria</label>
                            <select class="form-control select2" data-toggle="select2" id="categoria_create" name="id_categoria" required >
                                <option value="">Selecione ....</option>
                                @foreach ($categorias as $item)
                                <option value="{{ $item->id}} " style="text-transform: capitalize;" {{$item->nome == "Estrutura" ? 'selected' : ''}} >{{$item->nome}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Sub-Categoria</label>
                            <select class="form-control select2" data-toggle="select2" name="id_subcategoria" required>
                                <option value="">Selecione ....</option>
                                @foreach ($subcategorias as $item)
                                <option value="{{ $item->id}} " style="text-transform: capitalize;" {{$item->nome == "Pagamento" ? 'selected' : ''}} >{{$item->nome}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-priority2">Intervalos de vencimento</label>
                            <select type="text" class="form-control"  name="intervalo" required>
                                <option value="7">Semanal</option>
                                <option value="15">Quinzenal</option>
                                <option value="30" selected >Mensal</option>
                            </select>
                        </div>
                    </div>




                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-title"> Data Venda</label>
                            <input type="date" class="form-control form-control-light"  name="vencimento" required>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-title"> Data 1º Vencimento</label>
                            <input type="date" class="form-control form-control-light" name="pri_vencimento" required>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Valor Parcela</label>
                            <input type="text" class="form-control form-control-light" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="valor_parcela" name="valor_parcela" required>

                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group">
                            <label for="task-priority2">Parcela</label>
                            <input type="text" class="form-control form-control-light" name="parcela" id="parcela" required>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-priority2">Valor do Lançamento</label>
                            <input type="text" class="form-control form-control-light" data-toggle="input-mask" data-mask-format="###0.00" data-reverse="true" name="valor_lancamento" id="valor_lancamento" required>
                            
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="task-priority2">Descrição</label>
                            <input type="text" class="form-control form-control-light"  name="descricao" required>
                        </div>
                    </div>

                </div>

                <div class="text-right mt-5">
                    <a href="{{ URL::previous()}}" class="btn btn-light" data-dismiss="modal">Sair</a>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
            </div>
       </div>
    </div> <!-- container -->

@endsection

@section('js')
<script>

    $(document).ready(function() {


        $('#valor_lancamento').focus( function (event){
            event.preventDefault();
            var parcela     =  $('#parcela').val();
            var valor_lanc  =  $('#valor_lancamento').val();
            var valor_parcela  =  $('#valor_parcela').val();

            if(!parcela || parcela == 0){
                $('#valor_lancamento').val(parseFloat(valor_parcela).toFixed(2));
                $('#parcela').val('A Vista');
            } else {
                var valor_lanc = parseFloat(valor_parcela) * parseInt(parcela);
                $('#valor_lancamento').val(valor_lanc.toFixed(2));
            }
        });




    } );
</script>
@endsection

resources/views/content/financeiros/despesas/playOf.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('despesas.index')}}">Despesa</a></li>
                            <li class="breadcrumb-item active">Efetuar Pagamento</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Efetuar Pagamento</h4>
                </div>
            </div>
        </div>
       <div class="card">
           
           <div class="card-body">
               <form class="p-2" method="POST" action="{{ route('lancamentos.update',$despesa->id) }}"> 
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Conta Bancária </label>
                            <select class="form-control select2" data-toggle="select2" name="conta_bancaria" required>
                                <option value="" style="text-transform: capitalize;" >Selecione uma conta bancária</option>
                               @foreach ($contas as $item)
                               @foreach ($bancos as $banco)
                                    @if ($banco['id']  == $item->banco)
                                    <option value="{{ $item->id}}" style="text-transform: capitalize;" >{{$banco['nome']}} ( {{$item->conta}} ) </option>
                                    @endif
                                @endforeach
                                    
                               @endforeach
                            </select> 
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Nome </label>
                            <select class="form-control select2" data-toggle="select2" name="id_cli" disabled>
                                <option value="{{ $lancamento->cliente->id}}" style="text-transform: capitalize;" >{{$lancamento->cliente->nome}} --- {{$lancamento->cliente->cpf}}</option>
                            </select> 
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Tipo</label>
                            <input type="text" class="form-control form-control-light"  name="tipo"  value="{{ $lancamento->tipo }}" readonly>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="task-priority2">Descrição</label>
                            <input type="text" class="form-control form-control-light"  name="descricao"  value="{{ $lancamento->descricao }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Parcela</label>
                            <input type="text" class="form-control form-control-light"  name="parcela"  value="{{ $despesa->parcela }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Valor Parcela</label>
                            <input type="text" class="form-control form-control-light"  name="valor_parcela"  value="{{ $despesa->valor_parcela }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-priority2">Valor a Pagar</label>
                            <input type="text" class="form-control form-control-light" data-toggle="input-mask" data-mask-format="###0.00" data-reverse="true" name="valor_a_pagar" >
                        </div>
                    </div>
                </div>
    
                <div class="text-right mt-5">
                    <a href="{{ URL::previous() }}" class="btn btn-light" >Sair</a>
                    <button type="submit" class="btn btn-primary">Baixar</button>
                </div>
            </form>
           </div>
       </div>
    </div> <!-- container -->

@endsection

@section('js')
<script>
   
    $(document).ready(function() {
       
       
        $('#valor_parcela_create').focus( function (event){
            event.preventDefault();            
            var parcela     =  $('#parcela_create').val();
            var valor_lanc  =  $('#valor_lancamento_create').val();

            if(!parcela || parcela == 0){
                $('#valor_parcela_create').val(parseInt(valor_lanc).toFixed(2));
                $('#parcela_create').val('A Vista');
            } else {
                var valor_parcela = parseInt(valor_lanc) / parseInt(parcela);
                $('#valor_parcela_create').val(valor_parcela.toFixed(2));
            }
        });  

        
        
          
    } );
</script>
@endsection