routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\CustoController;
use App\Http\Controllers\SalarioController;
use App\Http\Controllers\PlanosController;
use App\Http\Controllers\ServicoAgenciadoController;
use App\Http\Controllers\BaseCustoController;
use App\Http\Controllers\CadastroDiversosFinancController;
use App\Http\Controllers\ContaController;
use App\Http\Controllers\CentroCustoController;
use App\Http\Controllers\CategoriaLancController;
use App\Http\Controllers\SubCategoriaLancController;
use App\Http\Controllers\LancamentoController;
use App\Http\Controllers\ReceitasController;
use App\Http\Controllers\DespesasController;
use App\Http\Controllers\FornecedoresController;
use App\Http\Controllers\PropostasController;
use App\Http\Controllers\LeadsController;
use App\Http\Controllers\GestaoAnuncioController;
use App\Http\Controllers\LinhaEditorialController;
use App\Http\Controllers\ProspeccaoController;
use App\Http\Controllers\ConversaController;
use App\Http\Controllers\ConsultoriaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ContratoController;
use App\Http\Controllers\ApresentacaoController;
use App\Http\Controllers\ContaBancariaController;
use App\Http\Controllers\PlataformaController;
use App\Http\Controllers\PlataformaItensController;
use App\Http\Controllers\GoogleAdsController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\PlanoGestaoController;
use App\Http\Livewire\Leads;



Auth::routes();
Route::get('/', [HomeController::class, 'index'])->name('home');



Route::group(['prefix' => 'pdf'], function () {
    Route::get('resumo/{id}', [PdfController::class, 'resumo'])->name('pdf.resumo');
    Route::get('recibo/{id}', [PdfController::class, 'recibo'])->name('pdf.recibo');
});



Route::group(['prefix' => 'gestao-financeira'], function () {
    Route::resource('custos', CustoController::class);
    Route::resource('custos-salarios', SalarioController::class);
    Route::resource('planos', PlanosController::class);
    Route::resource('servicos-agenciado', ServicoAgenciadoController::class);
    Route::resource('base-custos', BaseCustoController::class);
    Route::get('cadastros-diversos', [CadastroDiversosFinancController::class, 'index'])->name('cadastros.diversos');
    Route::resource('plano-contas', ContaController::class);
    Route::resource('centro-custos', CentroCustoController::class);
    Route::resource('categorias', CategoriaLancController::class);
    Route::resource('subcategorias', SubCategoriaLancController::class);
    Route::resource('lancamentos', LancamentoController::class);

    Route::resource('receitas', ReceitasController::class);
    Route::get('receitas/detal/{id}', [ReceitasController::class, 'detal'])->name('receitas.detal');

    Route::resource('despesas', DespesasController::class);
    Route::get('despesas/detal/{id}', [DespesasController::class, 'detal'])->name('despesas.detal');
    Route::post('despesas/relatorio', [DespesasController::class, 'relatorio'])->name('despesas.relatorio');


    Route::resource('contas-bancarias', ContaBancariaController::class);
    Route::resource('propostas', PropostasController::class);
    Route::get('propostas/invoice/{id}', [PropostasController::class, 'invoice'])->name('propostas.invoice');

    Route::resource('produtos', ProdutoController::class);

    
});

Route::group(['prefix' => 'gestao-pessoas'], function () {
    Route::get('clientes/{id}/active', [ClientesController::class, 'active'])->name('clientes.active');
    Route::resource('clientes', ClientesController::class);

    Route::get('fornecedores/{id}/active', [FornecedoresController::class, 'active'])->name('fornecedores.active');
    Route::resource('fornecedores', FornecedoresController::class);

    Route::get('leads/{id}/active', [LeadsController::class, 'active'])->name('leads.active');
    Route::resource('leads-controller', LeadsController::class);

    Route::get('usuarios/{id}/funcoes',[UserController::class, 'funcoes'])->name('usuarios.funcoes');
    Route::put('usuarios/{id}/funcoes/sync',[UserController::class, 'funcoesSync'])->name('usuarios.funcoesSync');
    Route::resource('usuarios', UserController::class);

    Route::get('funcoes/{id}/permissoes',[RoleController::class, 'permissoes'])->name('funcoes.permissoes');
    Route::put('funcoes/{id}/permissoes/sync',[RoleController::class, 'permissoesSync'])->name('funcoes.permissoesSync');
    Route::resource('funcoes', RoleController::class);

    Route::resource('permissoes', PermissionController::class);
    Route::get('leads', Leads::class);

});

Route::group(['prefix' => 'gestao-marketing'], function () {
    Route::get('consultorias/consultoria', [ConsultoriaController::class, 'consultoria'])->name('consultorias.consultoria');
    Route::post('consultorias/montar', [ConsultoriaController::class, 'montar'])->name('consultorias.montar');
    Route::resource('consultorias', ConsultoriaController::class);
    Route::resource('contratos', ContratoController::class);
    Route::resource('apresentacao', ApresentacaoController::class);

    Route::get('gestao-anuncios/{id}/relatorio', [GestaoAnuncioController::class, 'relatorio'])->name('gestao-anuncios.relatorio');
    Route::resource('gestao-anuncios', GestaoAnuncioController::class);
});

Route::group(['prefix' => 'configuracao'], function () {
    Route::resource('plataformas', PlataformaController::class);
    Route::resource('plataforma-itens', PlataformaItensController::class);
    Route::resource('planos-gestao', PlanoGestaoController::class);
});

app/Models/Plano.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Plano extends Model
{
    protected $table  = 'planos';
    protected $fillable = ['id', 'nome', 'plano_base'];

    public function itens()
    {
        return $this->hasMany(ItensPlano::class, 'id_plano', 'id');
    }
}

app/Http/Controllers/PlanosController.php
<?php

namespace App\Http\Controllers;

use App\Models\BaseCusto;
use App\Models\ItensPlano;
use App\Models\Plano;
use App\Models\Salario;
use App\Models\ServicoAgenciado;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Collection;

class PlanosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $planos = Plano::where('id_empresa', Auth::user()->id_empresa)->get();

        return view('content.financeiros.planos.index', compact('planos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $servicos_agenciado = ServicoAgenciado::where('id_empresa', Auth::user()->id_empresa)->orderby('descricao')->get();
        $salarios = Salario::where('id_empresa', Auth::user()->id_empresa)->get();
        $base_custos = BaseCusto::where('id_empresa', Auth::user()->id_empresa)->first();

        if (count($salarios) > 0) {
            foreach ($salarios as $key => $value) {
                $gestor = (($salarios[1]->salario + $salarios[1]->total_provisoes) / 20) / 4.6;
                $operador = (($salarios[0]->salario + $salarios[0]->total_provisoes) / 20) / 4.6;
            }
        } else {
            $gestor = '0,00';
            $operador = '0,00';
        }

        return view('content.financeiros.planos.create', compact('servicos_agenciado', 'gestor', 'operador', 'base_custos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $plano = new Plano();
        $plano->id_empresa = Auth::user()->id_empresa;
        $plano->nome              = $request->nome;
        $plano->hora_gerenciar    = $request->hora_gerenciar;
        $plano->status            = $request->status;
        $plano->preco_plano_hora  = $request->preco_plano_hora;
        $plano->custo_operacional = $request->custo_operacional;
        $plano->margem_lucro      = $request->margem_lucro;
        $plano->impostos          = $request->impostos;
        $plano->valor_plano       = $request->valor_plano;
        $plano->plano_individual  = $request->valor_plano_individual;
        $plano->save();

        $relProdutos = $request->relProdutos;
        $dados =  json_decode($relProdutos);


        foreach ($dados as $key => $value) {
            $itens_plano = new ItensPlano();
            $itens_plano->id_empresa = $plano->id_empresa;
            $itens_plano->id_plano = $plano->id;
            $itens_plano->id_servico_agenciado = $value->id;
            $itens_plano->valor = $value->valor;
            $itens_plano->qtde = $value->qtde;
            $itens_plano->subtotal = $value->sub_total;
            $itens_plano->save();
        }

        return redirect()->route('planos.index')->with('success', 'store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('content.pdfs.resumo', compact('proposta', 'itensProposta', 'cliente', 'endereco', 'total'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $plano = Plano::where('id', $id)->first();
        $itens = ItensPlano::where('id_plano', $id)->get();
        $servicos_agenciado = ServicoAgenciado::where('id_empresa', Auth::user()->id_empresa)->orderby('descricao')->get();
        $salarios = Salario::where('id_empresa', Auth::user()->id_empresa)->get();
        $base_custos = BaseCusto::where('id_empresa', Auth::user()->id_empresa)->first();

        $produtos = collect([]);


        foreach ($itens as $key => $value) {
            $produto['descricao'] = $value->servico->descricao;
            $produto['id'] = $value->servico->id;
            $produto['esforco_valor'] = $value->servico->esforco_valor;
            $produto['valor'] = $value->valor;
            $produto['qtde'] = $value->qtde;
            $produto['sub_total'] = $value->subtotal;

            $produtos->push($produto);
        }
        //$produtos = $produtos->toJson();

        if (count($salarios) > 0) {
            foreach ($salarios as $key => $value) {

                $gestor = (($salarios[1]->salario + $salarios[1]->total_provisoes) / 20) / 4.6;
                $operador = (($salarios[0]->salario + $salarios[0]->total_provisoes) / 20) / 4.6;
            }
        } else {
            $gestor = '0,00';
            $operador = '0,00';
        }

      

        return view('content.financeiros.planos.edit', compact('plano', 'produtos', 'servicos_agenciado', 'gestor', 'operador', 'base_custos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $plano = Plano::where('id', $id)->first();
        $plano->id_empresa = Auth::user()->id_empresa;
        $plano->nome              = $request->nome;
        $plano->hora_gerenciar    = $request->hora_gerenciar;
        $plano->status            = $request->status;
        $plano->preco_plano_hora  = $request->preco_plano_hora;
        $plano->custo_operacional = $request->custo_operacional;
        $plano->margem_lucro      = $request->margem_lucro;
        $plano->impostos          = $request->impostos;
        $plano->valor_plano       = $request->valor_plano;
        $plano->plano_individual  = $request->valor_plano_individual;
        $plano->save();

        $relProdutos = $request->relProdutos;
        $dados =  json_decode($relProdutos);
        ItensPlano::where('id_plano', $id)->delete();

        if ($dados) {
            foreach ($dados as $key => $value) {
                $itens_plano = new ItensPlano();
                $itens_plano->id_empresa = $plano->id_empresa;
                $itens_plano->id_plano = $plano->id;
                $itens_plano->id_servico_agenciado = $value->id;
                $itens_plano->valor = $value->valor;
                $itens_plano->qtde = $value->qtde;
                $itens_plano->subtotal = $value->sub_total;
                $itens_plano->save();
            }
        }



        return redirect()->route('planos.index')->with('success', 'update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Plano $plano)
    {
        $plano->delete();
        ItensPlano::where('id_plano', $plano->id)->delete();
        return redirect()->route('planos.index')->with('success', 'destroy');
    }
}

resources/views/content/financeiros/planos/detalhes.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('planos.index')}}">Plano</a></li>
                            <li class="breadcrumb-item active">Editar Plano</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Editar Plano</h4>
                </div>
            </div>
        </div>
       <div class="card">
           <div class="card-body">
            <form>
                <input type="hidden" name="relProdutos" id="relProdutos">
                @csrf
                <div class="row">
                    <div class="col-xl-12">
                        <!-- tasks panel -->
                        <div class="collapse show" id="todayTasks">
                            <div class="card mb-0">
                                <div class="card-body">
                                    <a class="text-dark" data-toggle="collapse" href="#todayTasks" aria-expanded="false" aria-controls="todayTasks">
                                        <h4 class="m-0 pb-2">
                                            <i class="uil uil-angle-down font-18"></i>Detalhes Planos <span class="text-muted"></span>
                                        </h4>
                                    </a>
                                    <hr>
                                    <div class="row">
                                        <div class="col-xl-4">
                                            <div class="form-group cliente">
                                                <h4 class="mb-0 mt-2">Nome</h4>
                                                <input type="text" name="nome" class="form-control" value="{{ $plano->nome }}">
                                            </div>
                                        </div> <!-- end col-->
                                        <div class="col-xl-2">

                                        </div> <!-- end col-->
                                        <div class="col-xl-4">

                                        </div> <!-- end col-->
                                        <div class="col-xl-2">
                                            <h4 class="mb-0 mt-2">Status</h4>
                                            <select name="status" id="status" class="form-control">
                                                <option value="{{$plano->status}}" {{$plano->status == 'ativo' ? 'selected' :''}} >Ativo</option>
                                                <option value="{{$plano->status}}" {{$plano->status == 'inativo' ? 'selected' :''}}>Inativo</option>
                                            </select>
                                        </div> <!-- end col-->
                                    </div>
                                    <!-- end row -->
                                </div>
                            </div> <!-- end card -->
                        </div> <!-- end .collapse-->
                        <br>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-8">

                                <div class="table-responsive">
                                    <table class="table table-borderless table-centered mb-0 no-wrap"  id="Table" style=" max-height: 150px;" >
                                        <thead class="thead-light">
                                            <tr>
                                                <th>#</th>
                                                <th>Descricao</th>
                                                <th style="width: 50px"></th>
                                            </tr>
                                        </thead>
                                        <tbody style="height-max:400px">
                                            @foreach ($itens as $item)
                                            <tr>
                                            <td>{{ $item->id}}</td>
                                                <td>{{ $item->servico->nome}}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div> <!-- end table-responsive-->

                                <!-- action buttons-->
                                <div class="row mt-4">
                                    <div class="col-sm-6">
                                        <a href="{{ URL::previous() }}" class="btn text-muted d-none d-sm-inline-block btn-link font-weight-semibold">
                                            <i class="mdi mdi-arrow-left"></i> Voltar  </a>
                                    </div> <!-- end col -->
                                    <div class="col-sm-6">
                                        <div class="text-sm-right">

                                        </div>
                                    </div> <!-- end col -->
                                </div> <!-- end row-->
                            </div>
                            <!-- end col -->

                            <div class="col-lg-4">
                                <div class="border p-3 mt-4 mt-lg-0 rounded">
                                    <h4 class="header-title mb-3">Resumo da Proposta</h4>

                                    <div class="table-responsive">
                                        <table class="table mb-0">
                                            <tbody>
                                                <tr>
                                                    <td>Plano Base</td>
                                                    <td>
                                                    <input type="text" name="plano_base" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="plano_base" class="form-control" value="{{ $plano->plano_base }}">

                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Gerenciamento: </td>
                                                    <td>
                                                    <input type="text" name="gerenciamento" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="gerenciamento" class="form-control" value="{{ $plano->gerenciamento }}">

                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Margem Lucro</td>
                                                    <td>
                                                        <input type="text" name="margem_lucro"  id="margem_lucro" class="form-control" value="{{ $plano->margem_lucro }}">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Impostos</td>
                                                    <td>
                                                        <input type="text" name="impostos" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="impostos" class="form-control" value="{{ $plano->impostos }}">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Valor do Plano</td>
                                                    <td>
                                                        <input type="text" name="valor_plano" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="valor_plano" class="form-control" value="{{ $plano->valor_plano }}">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Plano Individual</td>
                                                    <td>
                                                        <input type="text" name="valor_plano_individual" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" id="valor_plano_individual" class="form-control" value="{{ $plano->plano_individual }}">
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end table-responsive -->
                                </div>

                            </div> <!-- end col -->

                        </div> <!-- end row -->
                    </div>
                </div>
            </form>
           </div>
       </div>
    </div> <!-- container -->
@endsection

resources/views/content/financeiros/planos/playOf.blade.php
@extends('layouts.app')
@section('content')

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('despesas.index')}}">Despesa</a></li>
                            <li class="breadcrumb-item active">Receber Pagamento</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Pagar Despesa</h4>
                </div>
            </div>
        </div>
       <div class="card">
           
           <div class="card-body">
               <form class="p-2" method="POST" action="{{ route('lancamentos.update',$despesa->id) }}"> 
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label>Nome </label>
                            <select class="form-control select2" data-toggle="select2" name="id_cli" disabled>
                                <option value="{{ $lancamento->cliente->id}}" style="text-transform: capitalize;" >{{$lancamento->cliente->nome}} --- {{$lancamento->cliente->cpf}}</option>
                            </select> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="task-priority2">Tipo</label>
                            <input type="text" class="form-control form-control-light"  name="tipo"  value="{{ $lancamento->tipo }}" readonly>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="task-priority2">Descrição</label>
                            <input type="text" class="form-control form-control-light"  name="descricao"  value="{{ $lancamento->descricao }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Parcela</label>
                            <input type="text" class="form-control form-control-light"  name="parcela"  value="{{ $despesa->parcela }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="task-priority2">Valor Parcela</label>
                            <input type="text" class="form-control form-control-light"  name="valor_parcela"  value="{{ $despesa->valor_parcela }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="task-priority2">Valor a Pagar</label>
                            <input type="text" class="form-control form-control-light" data-toggle="input-mask" data-mask-format="#.##0.00" data-reverse="true" name="valor_a_pagar" >
                        </div>
                    </div>
                </div>
    
                <div class="text-right mt-5">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Sair</button>
                    <button type="submit" class="btn btn-primary">Baixar</button>
                </div>
            </form>
           </div>
       </div>
    </div> <!-- container -->

@endsection

@section('js')
<script>
   
    $(document).ready(function() {
       
       
        $('#valor_parcela_create').focus( function (event){
            event.preventDefault();            
            var parcela     =  $('#parcela_create').val();
            var valor_lanc  =  $('#valor_lancamento_create').val();

            if(!parcela || parcela == 0){
                $('#valor_parcela_create').val(parseInt(valor_lanc).toFixed(2));
                $('#parcela_create').val('A Vista');
            } else {
                var valor_parcela = parseInt(valor_lanc) / parseInt(parcela);
                $('#valor_parcela_create').val(valor_parcela.toFixed(2));
            }
        });  

        
        
          
    } );
</script>
@endsection